/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Studies */
        post: operations["sync_studies_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Changes */
        get: operations["list_changes_api_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changes/{change_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Change Detail */
        get: operations["change_detail_api_changes__change_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Decide Action */
        patch: operations["decide_action_api_actions__action_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Studies */
        get: operations["list_studies_api_studies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIAnalysis */
        AIAnalysis: {
            /** Headline */
            headline: string;
            /** Summary */
            summary: string;
            /** Possible Significance */
            possible_significance: string[];
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
        };
        /** AuditEntryView */
        AuditEntryView: {
            /** Id */
            id: number;
            /** Action Id */
            action_id: number;
            /** Action Title */
            action_title: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChangeDetail */
        ChangeDetail: {
            /** Id */
            id: number;
            /** Nct Id */
            nct_id: string;
            /** Title */
            title: string;
            /** Sponsor */
            sponsor: string;
            /**
             * Source
             * @enum {string}
             */
            source: "live" | "replay";
            /** Label */
            label: string;
            /** Source Url */
            source_url: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "critical" | "high" | "medium" | "low";
            /** Category */
            category: string;
            /** Headline */
            headline: string;
            /** Review Status */
            review_status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Structured Diff */
            structured_diff: components["schemas"]["FieldChange"][];
            before: components["schemas"]["SnapshotEvidence"];
            after: components["schemas"]["SnapshotEvidence"];
            ai_analysis: components["schemas"]["AIAnalysis"] | null;
            /** Actions */
            actions: components["schemas"]["FollowUpActionView"][];
            /** Audit Timeline */
            audit_timeline: components["schemas"]["AuditEntryView"][];
        };
        /** ChangeSummary */
        ChangeSummary: {
            /** Id */
            id: number;
            /** Nct Id */
            nct_id: string;
            /** Title */
            title: string;
            /** Sponsor */
            sponsor: string;
            /**
             * Source
             * @enum {string}
             */
            source: "live" | "replay";
            /** Label */
            label: string;
            /** Source Url */
            source_url: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "critical" | "high" | "medium" | "low";
            /** Category */
            category: string;
            /** Headline */
            headline: string;
            /** Review Status */
            review_status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DecisionRequest */
        DecisionRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "approved" | "rejected";
        };
        /** FieldChange */
        FieldChange: {
            /** Field */
            field: string;
            /** Before */
            before: unknown;
            /** After */
            after: unknown;
        };
        /** FollowUpActionView */
        FollowUpActionView: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "proposed" | "approved" | "rejected";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Intervention */
        Intervention: {
            /** Name */
            name: string;
            /** Type */
            type?: string | null;
            /** Description */
            description?: string | null;
        };
        /** Location */
        Location: {
            /** Facility */
            facility?: string | null;
            /** City */
            city?: string | null;
            /** State */
            state?: string | null;
            /** Zip */
            zip?: string | null;
            /** Country */
            country: string;
        };
        /** Outcome */
        Outcome: {
            /** Measure */
            measure: string;
            /** Time Frame */
            time_frame?: string | null;
            /** Description */
            description?: string | null;
        };
        /** Problem */
        Problem: {
            /** Detail */
            detail: string;
        };
        /** Snapshot */
        Snapshot: {
            /**
             * Overall Status
             * @enum {string}
             */
            overall_status: "ACTIVE_NOT_RECRUITING" | "COMPLETED" | "ENROLLING_BY_INVITATION" | "NOT_YET_RECRUITING" | "RECRUITING" | "SUSPENDED" | "TERMINATED" | "WITHDRAWN" | "AVAILABLE" | "NO_LONGER_AVAILABLE" | "TEMPORARILY_NOT_AVAILABLE" | "APPROVED_FOR_MARKETING" | "WITHHELD" | "UNKNOWN";
            /** Reason Stopped */
            reason_stopped?: string | null;
            /** Phases */
            phases: ("NA" | "EARLY_PHASE1" | "PHASE1" | "PHASE2" | "PHASE3" | "PHASE4")[];
            /** Enrollment Count */
            enrollment_count?: number | null;
            /** Primary Completion Date */
            primary_completion_date?: string | null;
            /** Completion Date */
            completion_date?: string | null;
            /** Interventions */
            interventions: components["schemas"]["Intervention"][];
            /** Primary Outcomes */
            primary_outcomes: components["schemas"]["Outcome"][];
            /** Eligibility Criteria */
            eligibility_criteria?: string | null;
            /** Countries */
            countries: string[];
            /** Locations */
            locations: components["schemas"]["Location"][];
        };
        /** SnapshotEvidence */
        SnapshotEvidence: {
            /** Id */
            id: number;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Content Hash */
            content_hash: string;
            normalised_data: components["schemas"]["Snapshot"];
        };
        /** Study */
        Study: {
            /** Nct Id */
            nct_id: string;
            /** Title */
            title: string;
            /** Lead Sponsor */
            lead_sponsor: string;
            /** Phases */
            phases: ("NA" | "EARLY_PHASE1" | "PHASE1" | "PHASE2" | "PHASE3" | "PHASE4")[];
            /**
             * Overall Status
             * @enum {string}
             */
            overall_status: "ACTIVE_NOT_RECRUITING" | "COMPLETED" | "ENROLLING_BY_INVITATION" | "NOT_YET_RECRUITING" | "RECRUITING" | "SUSPENDED" | "TERMINATED" | "WITHDRAWN" | "AVAILABLE" | "NO_LONGER_AVAILABLE" | "TEMPORARILY_NOT_AVAILABLE" | "APPROVED_FOR_MARKETING" | "WITHHELD" | "UNKNOWN";
            /**
             * Last Update Posted
             * Format: date
             */
            last_update_posted: string;
        };
        /** StudyList */
        StudyList: {
            /** Studies */
            studies: components["schemas"]["Study"][];
            /** Skipped */
            skipped: number;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
        };
        /** SyncResult */
        SyncResult: {
            /**
             * Source
             * @enum {string}
             */
            source: "live" | "replay";
            /** Label */
            label: string;
            /** Processed */
            processed: number;
            /** Skipped */
            skipped: number;
            /** Event Ids */
            event_ids: number[];
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
        };
        /** UpstreamProblem */
        UpstreamProblem: {
            /** Detail */
            detail: string;
            /** Upstream Status */
            upstream_status: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sync_studies_api_sync_post: {
        parameters: {
            query?: {
                mode?: "live" | "replay";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_changes_api_changes_get: {
        parameters: {
            query?: {
                source?: "live" | "replay";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    change_detail_api_changes__change_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                change_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    decide_action_api_actions__action_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowUpActionView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_studies_api_studies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyList"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpstreamProblem"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpstreamProblem"];
                };
            };
        };
    };
}
